### ISSUE TITLE
Some options could automatically imply others

### ISSUE THREAD

**Issue by chapulina** [colcon/colcon-package-information#29]
There are some options which currently only work in the presence of another one. For example, `colcon graph --dot-cluster` will not generate any dot output unless `--dot` is also passed in. Moreover, it fails quietly, giving the user no indication that `--dot` is missing. I think it would improve usability if options like `--dot-cluster` and `--dot-include-skipped` would automatically imply `--dot`, so users doesn't need to repeat themselves.

Speaking more generally, any option A that requires another option B and can't be used in any other way, could automatically imply that B is requested. This becomes especially neat in cases where A is a substring of B.

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request for the described improvement.

**Comment by dirk-thomas** [comment]
I will go ahead and close this ticket for now since there seems to be not enough interest to implement this minor convenience improvement.

Please feel free to just create a pull request for it.
